### ISSUE TITLE
event handler isn't invoked when changing active editor

### ISSUE THREAD

**Issue by shak1** [atom/dom-listener#3]
Hi,
I'm developing a package for atom in which i use dom-listener to catch click events on the number gutter.
this is the code i use in my package:

``` coffescript
listener = new DOMListener(document.querySelector('atom-text-editor::shadow .gutter .line-numbers'))
listener.add '.line-number', 'click', (event) ->
  console.log 'clicked'
```

this works only on the active editor( lets call it editor1) when i activate the package. Infact if i change tab then `clicked` isn't logged and then if i go back to editor1 the event handler is invoked.
Can you tell me where i'm wrong ? 
Thank you.
p.s. : sorry for my poor english, it is not my native language.

**Comment by izuzak** [comment]
@nathansobo Wondering if you have any advice?

**Comment by nathansobo** [comment]
@shak1 Unfortunately, this package doesn't work across shadow DOM boundaries. You'll need to attach the handler to the `.shadowRoot` of each text editor individually, then listen _without_ the `::shadow` selector.

``` coffee
listener = new DOMListener(document.querySelector('atom-text-editor').shadowRoot)
listener.add '.line-number', 'click', (event) ->
  console.log 'clicked'
```

Of course this means you'll need to create a handler for each editor on its own, rather than a global one that gets shared. This is an unfortunate drawback of using the shadow DOM in Atom, but for now it's the situation.
